version: '3.8'

services:
  flask_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Пробрасываем порт 5000
    volumes:
      - .:/app # Монтируем текущую директорию в контейнер
    environment:
      - FLASK_ENV=development # Устанавливаем режим разработки
    command: python app.py # Запускаем Flask приложение